version: '3'   # compose-file的语法版本
services:    # 定义服务
    web:      # 指定服务1 web
        build: .    # 使用当前目录下的Dockerfile构建镜像
        environment:
            - HOST_OPTS=${HOSTNAME}  # 需要设置好环境变量：export HOSTNAME=`hostname`
        ports:    # 指定端口映射
            - "9999:9999"
        container_name: flask  # 容器名称 container_name+services_name 会作为镜像名称
        #volumes:
        #    - app:/app
        depends_on:
            - redis
    redis:
        image: redis
        #volumes: 
        #    - redis-data:/data
        container_name: db
        command: redis-server --port 6379 --requirepass 123456
        ports:
            - 6379:6379

